#!/bin/bash

_kill_procs() {
  kill -TERM $firefox
  wait $firefox
}

# Setup a trap to catch SIGTERM and relay it to child processes
trap _kill_procs SIGTERM

firefox-original $@ &
firefox=$!

wait $firefox
